### ISSUE TITLE
Support for modulo (%)

### ISSUE THREAD

**Issue by ywarnier** [dbojdo/eval-math#3]
Hi, we use your lib in Chamilo LMS.
Do you have any intention of supporting the modulo (%) operation?
For example: 3%2 = 1, 7%4=3, etc.
I was a bit surprised to have + - * / ^ and _ but not %... (more than anything because it seems pretty easy to add).

**Comment by dbojdo** [comment]
Hi!
As title states this repository is just a Composer Version of EvalMath by Miles Kaufman lib. However I don't mind if you're going to add new operators support. If you find it easy, please implement this, test for backward compatibility, open pull request than I'll create a new version.

**Comment by ywarnier** [comment]
Miles Kaufman website is kind of anti-social (just a logo), so I couldn't contact him. I'll try to send a PR (or have someone send it) soon.

**Comment by MuslimAKhan** [comment]
Hi, have any method to do give error when input like this cos(a)+sin(c)*tan(f)--sqrt(d)/pi(o) equation? -- decrement operator should not accepted by class but give error. what should be done for it? have any method to reject this type of equation?

**Comment by dbojdo** [comment]
@ywarnier I've added support for modulo operator (see https://github.com/dbojdo/eval-math/blob/master/tests/EvalMathTest.php)

**Comment by ywarnier** [comment]
Great, thanks! Sorry I couldn't do it faster. Been busy with our own free software :+1:

**Comment by MuslimAKhan** [comment]
Your Welcome, I faced this issue in practical so i asked to you this
question. Thanks to you also that you have accept my view.

**Comment by ywarnier** [comment]
@dbojdo We have integrated the new version to Chamilo LMS https://github.com/chamilo/chamilo-lms/commit/da8bce63019338ab1261a6b1be75adbf2f99d340

We should be releasing a new version of Chamilo in a few weeks time, so this will be used by a few people, probably. Modulo was missing because we use it in a feature called "Calculated answer" where we generate a set of possible answers for an equation-type question: "Judy has [x] apples. How many apples are left after she distributes them equally between her [y] brothers?". Obviously, in this case you need to use the modulo operation in order to get the right number of apples left.
You can try it out on https://unstable.chamilo.org/main/exercice/overview.php?cidReq=OPEN&exerciseId=4 if you want to see how it looks

It was not a high priority on our list, but it still very nice to have it. Thanks.
