### ISSUE TITLE
Addition not working as expected

### ISSUE THREAD

**Issue by dtrupcevic** [dbojdo/eval-math#4]
While trying to use this library, I've come upon a weird issue

I have defined a simple addition expression

```php
    $m = new EvalMath;
    $m->evaluate("f(d,e,g)=d+e+g")
    $r = $m->evaluate("f(5,10,15)")
```

`$r` turned out to be 22.71something, which is obviously wrong. 

I've tested it in isolation with different inputs, and I'm getting consistently wrong results for simple addition.

```php
$m = new Webit\Util\EvalMath\EvalMath;

$m->evaluate("f(a,b,c,d,e,f)=a + b + c + d + e + f");

$res = $m->evaluate("f(1,1,1,1,1,1)");

var_dump($res);die;
```

yields
float(7.718281828459)

Anyone else had this issue?

**Comment by dbojdo** [comment]
"e" in this case is a reserved symbol for Euler's number which is about 2.718281828459 - use different one instead

**Comment by dtrupcevic** [comment]
Ah, thanks - stupidly overlooked this.
