### ISSUE TITLE
-- decrement operator accepted by eval class

### ISSUE THREAD

**Issue by MuslimAKhan** [dbojdo/eval-math#5]
Hi, have any method to do give error when input like this cos(a)+sin(c)*tan(f)--sqrt(d)/pi(o) equation? -- decrement operator should not accepted by class but give error. what should be done for it? have any method to reject this type of equation?

**Comment by dbojdo** [comment]
@MuslimAKhan In Maths "--" is not a decrement operator but is considered as "+" what is perfectly fine.
See attached test for this operator (https://github.com/dbojdo/eval-math/blob/master/tests/EvalMathTest.php#L64). This behaviour is correct and it won't be changed.

**Comment by dbojdo** [comment]
@MuslimAKhan to be more strict a--b is evaluated to a-(-1)*b (just a first example: http://www.purplemath.com/modules/negative2.htm)
